last: 1000
images:
  docker.elastic.co:
    # - elasticsearch/elasticsearch
    # - kibana/kibana
    # - logstash/logstash
    # - beats/filebeat
    # - beats/heartbeat
    # - beats/packetbeat
    # - beats/auditbeat
    # - beats/journalbeat
    # - beats/metricbeat
    # - apm/apm-server
    # - app-search/app-search
  quay.io:
    - coreos/flannel
    # - ceph/ceph
    # - cephcsi/cephcsi
    # - csiaddons/k8s-sidecar
    # - csiaddons/volumereplication-operator
     - prometheus/prometheus
     - prometheus/alertmanager
     - prometheus/pushgateway
     - prometheus/blackbox-exporter
     - prometheus/node-exporter
     - prometheus-operator/prometheus-config-reloader
     - prometheus-operator/prometheus-operator
    # - brancz/kube-rbac-proxy
    # - cilium/cilium
    # - cilium/operator-generic
     - thanos/thanos
    # - cilium/certgen
    # - cilium/hubble-relay
    # - cilium/hubble-ui-backend
    # - cilium/hubble-ui
    # - cilium/cilium-etcd-operator
    # - cilium/operator
    # - cilium/startup-script
    # - cilium/clustermesh-apiserver
    - coreos/etcd
  k8s.gcr.io:
    # - dns/k8s-dns-node-cache
    # - metrics-server/metrics-server
    # - kube-state-metrics/kube-state-metrics
    # - prometheus-adapter/prometheus-adapter
    # - sig-storage/nfs-subdir-external-provisioner
    # - sig-storage/csi-node-driver-registrar
    # - sig-storage/csi-provisioner
    # - sig-storage/csi-resizer
    # - sig-storage/csi-snapshotter
    # - sig-storage/csi-attacher
    # - sig-storage/nfsplugin
  registry.k8s.io:
    #- pause
    #- etcd
    #- conformance
    #- kube-proxy
    #- kube-apiserver
    #- kube-scheduler
    #- kube-controller-manager
    #- coredns/coredns
    #- defaultbackend-amd64
    #- ingress-nginx/controller
    #- ingress-nginx/opentelemetry
    #- ingress-nginx/controller-chroot
    # - ingress-nginx/kube-webhook-certgen
    # - cpa/cluster-proportional-autoscaler
    # - autoscaling/addon-resizer
  gcr.io:
    # - kaniko-project/executor
    # - google-samples/xtrabackup
  docker.io:
    #- calico/node
    #- calico/typha
    #- calico/cni
    #- calico/node
    #- calico/kube-controllers
    - goharbor/nginx-photon
    - goharbor/harbor-portal
    - goharbor/harbor-core
    - goharbor/harbor-jobservice
    - goharbor/registry-photon
    - goharbor/harbor-registryctl
    - goharbor/chartmuseum-photon
    - goharbor/trivy-adapter-photon
    - goharbor/notary-server-photon
    - goharbor/notary-signer-photon
    - goharbor/harbor-db
    - goharbor/redis-photon
    - goharbor/harbor-exporter
    # - calico/pod2daemon-flexvol
